<?php

return array(
	// Classes in includes/core/
	'Smartcrawl_AIOSEOP_Importer'               => '/core/class-wds-aioseop-importer.php',
	'Smartcrawl_Base_Controller'                => '/core/class-wds-base-controller.php',
	'Smartcrawl_Canonical_Value_Helper'         => '/core/class-wds-canonical-value-helper.php',
	'Smartcrawl_Checks'                         => '/core/class-wds-checks.php',
	'Smartcrawl_Compatibility'                  => '/core/class-wds-compatibility.php',
	'Smartcrawl_Controller_Analysis'            => '/core/class-wds-controller-analysis.php',
	'Smartcrawl_Controller_Assets'              => '/core/class-wds-controller-assets.php',
	'Smartcrawl_Controller_Checkup_Progress'    => '/core/class-wds-controller-checkup-progress.php',
	'Smartcrawl_Controller_Cron'                => '/core/class-wds-controller-cron.php',
	'Smartcrawl_Controller_Hub'                 => '/core/class-wds-controller-hub.php',
	'Smartcrawl_Controller_IO'                  => '/core/class-wds-controller-io.php',
	'Smartcrawl_Controller_Onboard'             => '/core/class-wds-controller-onboard.php',
	'Smartcrawl_Controller_Pointers'            => '/core/class-wds-controller-pointers.php',
	'Smartcrawl_Controller_Sitemap'             => '/core/class-wds-controller-sitemap.php',
	'Smartcrawl_White_Label'                    => '/core/class-wds-white-label.php',
	'Smartcrawl_Core_Request'                   => '/core/class-wds-core-request.php',
	'Smartcrawl_Endpoint_Resolver'              => '/core/class-wds-endpoint-resolver.php',
	'Smartcrawl_Export'                         => '/core/class-wds-export.php',
	'Smartcrawl_Html'                           => '/core/class-wds-html.php',
	'Smartcrawl_Import'                         => '/core/class-wds-import.php',
	'Smartcrawl_Importer'                       => '/core/class-wds-importer.php',
	'Smartcrawl_Logger'                         => '/core/class-wds-logger.php',
	'Smartcrawl_Macro'                          => '/core/class-wds-macro.php',
	'Smartcrawl_Meta_Value_Helper'              => '/core/class-wds-meta-value-helper.php',
	'Smartcrawl_Model'                          => '/core/class-wds-model.php',
	'Smartcrawl_Model_Analysis'                 => '/core/class-wds-model-analysis.php',
	'Smartcrawl_Model_Ignores'                  => '/core/class-wds-model-ignores.php',
	'Smartcrawl_Model_IO'                       => '/core/class-wds-model-io.php',
	'Smartcrawl_Model_Redirection'              => '/core/class-wds-model-redirection.php',
	'Smartcrawl_Model_User'                     => '/core/class-wds-model-user.php',
	'Smartcrawl_Renderable'                     => '/core/class-wds-renderable.php',
	'Smartcrawl_Replacement_Helper'             => '/core/class-wds-replacement-helper.php',
	'Smartcrawl_Simple_Renderer'                => '/core/class-wds-simple-renderer.php',
	'Smartcrawl_Reset'                          => '/core/class-wds-reset.php',
	'Smartcrawl_OpenGraph_Value_Helper'         => '/core/class-wds-opengraph-value-helper.php',
	'Smartcrawl_Robots_Value_Helper'            => '/core/class-wds-robots-value-helper.php',
	'Smartcrawl_SeoReport'                      => '/core/class-wds-seo-report.php',
	'Smartcrawl_Service'                        => '/core/class-wds-service.php',
	'Smartcrawl_Settings'                       => '/core/class-wds-settings.php',
	'Smartcrawl_String'                         => '/core/class-wds-string.php',
	'Smartcrawl_Type_Traverser'                 => '/core/class-wds-type-traverser.php',
	'Smartcrawl_WorkUnit'                       => '/core/class-wds-work-unit.php',
	'Smartcrawl_Yoast_Importer'                 => '/core/class-wds-yoast-importer.php',
	// Classes in includes/core/service/
	'Smartcrawl_Checkup_Ajax_Service'           => '/core/service/class-wds-checkup-ajax-service.php',
	'Smartcrawl_Checkup_Rest_Service'           => '/core/service/class-wds-checkup-rest-service.php',
	'Smartcrawl_Checkup_Service_Implementation' => '/core/service/class-wds-checkup-service-implementation.php',
	'Smartcrawl_Checkup_Service'                => '/core/service/class-wds-checkup-service.php',
	'Smartcrawl_Seo_Service'                    => '/core/service/class-wds-seo-service.php',
	'Smartcrawl_Site_Service'                   => '/core/service/class-wds-site-service.php',
	'Smartcrawl_Uptime_Service'                 => '/core/service/class-wds-uptime-service.php',
	// Classes in includes/core/checks/
	'Smartcrawl_Check_Post_Abstract'            => '/core/checks/class-wds-check-post-abstract.php',
	'Smartcrawl_Check_Abstract'                 => '/core/checks/class-wds-check-abstract.php',
	'Smartcrawl_Check_Content_Length'           => '/core/checks/class-wds-check-content-length.php',
	'Smartcrawl_Check_Focus'                    => '/core/checks/class-wds-check-focus.php',
	'Smartcrawl_Check_Focus_Stopwords'          => '/core/checks/class-wds-check-focus-stopwords.php',
	'Smartcrawl_Check_Imgalts_Keywords'         => '/core/checks/class-wds-check-imgalts-keywords.php',
	'Smartcrawl_Check_Keyword_Density'          => '/core/checks/class-wds-check-keyword-density.php',
	'Smartcrawl_Check_Keywords_Used'            => '/core/checks/class-wds-check-keywords-used.php',
	'Smartcrawl_Check_Links_Count'              => '/core/checks/class-wds-check-links-count.php',
	'Smartcrawl_Check_Metadesc_Keywords'        => '/core/checks/class-wds-check-metadesc-keywords.php',
	'Smartcrawl_Check_Metadesc_Length'          => '/core/checks/class-wds-check-metadesc-length.php',
	'Smartcrawl_Check_Para_Keywords'            => '/core/checks/class-wds-check-para-keywords.php',
	'Smartcrawl_Check_Slug_Keywords'            => '/core/checks/class-wds-check-slug-keywords.php',
	'Smartcrawl_Check_Subheadings_Keywords'     => '/core/checks/class-wds-check-subheadings-keywords.php',
	'Smartcrawl_Check_Title_Keywords'           => '/core/checks/class-wds-check-title-keywords.php',
	'Smartcrawl_Check_Title_Length'             => '/core/checks/class-wds-check-title-length.php',
	// Classes in includes/admin/
	'Smartcrawl_Admin'                          => '/admin/admin.php',
	'Smartcrawl_Metabox'                        => '/admin/metabox.php',
	'Smartcrawl_Settings_Admin'                 => '/admin/settings.php',
	'Smartcrawl_Taxonomy'                       => '/admin/taxonomy.php',
	'Smartcrawl_Autolinks_UI'                   => '/admin/class-wds-autolinks-ui.php',
	'Smartcrawl_OnPage_UI'                      => '/admin/class-wds-onpage-ui.php',
	'Smartcrawl_SEO_Analysis_UI'                => '/admin/class-wds-seo-analysis-ui.php',
	'Smartcrawl_Readability_Analysis_UI'        => '/admin/class-wds-readability-analysis-ui.php',
	'Smartcrawl_Social_UI'                      => '/admin/class-wds-social-ui.php',
	'Smartcrawl_Sitemap_UI'                     => '/admin/class-wds-sitemap-ui.php',
	// Classes in includes/admin/settings/
	'Smartcrawl_Autolinks_Settings'             => '/admin/settings/autolinks.php',
	'Smartcrawl_Checkup_Settings'               => '/admin/settings/checkup.php',
	'Smartcrawl_Settings_Dashboard'             => '/admin/settings/dashboard.php',
	'Smartcrawl_Onpage_Settings'                => '/admin/settings/onpage.php',
	'Smartcrawl_Settings_Settings'              => '/admin/settings/settings.php',
	'Smartcrawl_Sitemap_Settings'               => '/admin/settings/sitemap.php',
	'Smartcrawl_Social_Settings'                => '/admin/settings/social.php',
	// Classes in includes/tools/
	'Smartcrawl_Autolinks'                      => '/tools/autolinks.php',
	'Smartcrawl_OpenGraph_Printer'              => '/tools/class-wds-opengraph-printer.php',
	'Smartcrawl_Pinterest_Printer'              => '/tools/class-wds-pinterest-printer.php',
	'Smartcrawl_Schema_Printer'                 => '/tools/class-wds-schema-printer.php',
	'Smartcrawl_Social_Front'                   => '/tools/class-wds-social-front.php',
	'Smartcrawl_Twitter_Printer'                => '/tools/class-wds-twitter-printer.php',
	'Smartcrawl_OnPage'                         => '/tools/onpage.php',
	'Smartcrawl_Redirection_Front'              => '/tools/redirect.php',
	'Smartcrawl_Xml_Sitemap'                    => '/tools/sitemaps.php',
	'Smartcrawl_Sitemaps_Dashboard_Widget'      => '/tools/sitemaps-dashboard-widget.php',
	'Smartcrawl_Xml_VideoSitemap'               => '/tools/video-sitemaps.php',
	// Classes in includes/tools/seomoz/
	'Smartcrawl_Moz_API'                        => '/tools/seomoz/class-wds-moz-api.php',
	'Smartcrawl_Moz_Dashboard_Widget'           => '/tools/seomoz/class-wds-moz-dashboard-widget.php',
	'Smartcrawl_Moz_Results_Renderer'           => '/tools/seomoz/class-wds-moz-results-renderer.php',
	'Smartcrawl_Moz_Metabox'                    => '/tools/seomoz/class-wds-moz-metabox.php',
	// Classes in includes/
	'Smartcrawl_Front'                          => '/front.php',
);
